site_name: hello-NOO Python Package
site_url: https://neonorangeorange.github.io/hello-NOO/ 
repo_url: https://github.com/NeonOrangeOrange/hello-NOO
edit_uri: ""

theme:
  name: readthedocs

nav:
  - "Home": index.md
  - "Making a Python Project": making-a-python-project.md
  - "Documentation Guide": documentation-guide.md
  - "Packaging Guide": packaging-guide.md
