[project]
name = "hello-NOO"
version = "0.0.1"
authors = [
  { name="NeonOrangeOrange", email="neonorangeorange@gmail.com" }
]
description = "A small example package"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]


